spring:
  application:
    name: riyadmanager
  datasource:
    url: jdbc:mysql://localhost:3306/riyadmanager_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace 
      springframework:
        web: DEBUG
        security: DEBUG
        data: DEBUG
    com:
      marouanedbibih: Debug
